services:
  tracker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tracker
    ports:
      - "8000:8000"
    networks:
      - torrent-net

  transmission-seeder:
    image: alpine:latest
    volumes:
      - ./seeder_data:/data
      - ./scripts/start_transmission_seeding.sh:/start_transmission_seeding.sh:ro
    ports:
      - "51413:51413" # BitTorrent port
    networks:
      - torrent-net
    depends_on:
      - tracker
    command: ["sh", "/start_transmission_seeding.sh"]
    tty: true
    stdin_open: true

  leecher:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bittorrent-cli
    volumes:
      - ./downloads:/home/appuser/Downloads/Torrents
      - ./seeder_data:/torrents:ro #read-only
    environment:
      - HOME=/home/appuser
    networks:
      - torrent-net
    depends_on:
      - tracker
      - transmission-seeder
    command: ["--log-level=info", "/torrents/test.torrent"]

networks:
  torrent-net:
    driver: bridge

volumes:
  downloads:
  transmission_config:
